name: Example Workflow

on:
  workflow_dispatch:
    inputs:
      trigger_id:
        description: 'ID used to detect the correct workflow run'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Print Hello, World!
        run: echo "Hello, World!"
