name: Example Inputs Workflow

on:
  workflow_dispatch:
    inputs:
      trigger_id:
        description: 'ID used to detect the correct workflow run'
      message:
        description: 'Message to print'
        required: true

jobs:
  example:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Print Message
        run: echo "${{ github.event.inputs.message }}"
